### ISSUE TITLE
Add game state that is synced between all users

### ISSUE THREAD

**Issue by gertgeringer** [mvtuong/drinking#1]
My initial thinking on a game state object:

```
export interface IUser {
    name: string;
    cursorLocation: [number, number];
}

export interface IGameState {
    activeUserName: string;
    pickedLocation: [number, number];
    imgUrl: string;
    users: IUser[];
}
```

This state can then be synced between the different user clients via a websocket connection.

**Comment by mvtuong** [comment]
Then we can find a way how to manage lucky player and allow her to select n player(s) each round. Only those (lucky one + selected players) are allowed to interact with the image with their name on it.

**Comment by gertgeringer** [comment]
Then I suggest we update the game state object to look as follows.

```
export interface IPlayer {
    name: string;
    cursorLocation: [number, number];
    selectedLocation: [number, number];
}

export interface IGameState {
    player: IPlayer[];
    level: ILevel;
}

export interface ILevel {
    imgUrl: string;
    luckyPlayer: IPlayer[];
    selectedPlayers: IPlayer[];
}
```

The game flow can then be

1. the lucky player selects other players (gamestate.level.selectedPlayers)
2. he is directed to the image view controller that loads the image URL (gamestate.level.imgUrl)
3. he selects the winning location on the image (gamestate.level.luckyPlayer.selectedLocation) and we create a hidden mesh at that location
4. the other players then have the opportunity to select locations on the image (gamestate.level.selectedPlayers[0].selectedLocation)
5. we intersect their chosen locations with the winning location
6. if hit then that player wins

**Comment by mvtuong** [comment]
Totally agree. To complete the entire flow, 2 more steps will be added:

Step 0. Game controller creates the game. Other players join. Game controller clicks on the start button to select the lucky one.
Then step 1. 2. 3. 4. 5. 6. (above)
Step 7. Game controller reveals the result.
